#!/usr/bin/env python3
"""Render the cross-field (advisory) contract rules the plugin authors against.

The rules live in the pinned `analitiq-contract-models` package as a registry
(`analitiq.contracts.shared.advisory.all_rules()`): each carries a stable
`ADV-*` id, the resource it constrains, a one-line normative statement, and the
model validator that enforces it. That registry is the single source of truth —
this script only *renders* it so agents have an offline-readable file to cite
instead of hand-restating rules in prose.

The generated file is a **pinned copy**, not a second source: `tests/connector_builder`
regenerates it and fails when it is stale, so a contract change surfaces as a red
build rather than silent prose drift.

Usage:
    render_advisory.py write    # regenerate the markdown file in place
    render_advisory.py check    # exit 1 if the file is stale (CI)
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# This repo is the contract's SOURCE, so bootstrap the same way render_schemas.py
# does rather than relying on an installed wheel — requirements-dev.txt
# deliberately does not install one. Keeps the script runnable standalone (CI
# calls it directly, outside pytest and its conftest).
sys.path.insert(0, str(REPO_ROOT / "packages" / "contract-models" / "src"))
# `analitiq.contracts.shared.common` reads os.environ["DOMAIN"] at import and
# raises KeyError without it.
os.environ.setdefault("DOMAIN", "analitiq.ai")
OUTPUT_PATH = (
    REPO_ROOT / "plugins" / "analitiq-connector-builder" / "skills" / "connector-builder" / "references" / "advisory-rules.md"
)

# Only the resources this plugin authors. Pipelines, streams, connection
# documents, and database endpoints are owned elsewhere (database endpoints are
# produced by the connector's `resource_discovery` at runtime, never authored
# here), so their rules are noise in an authoring reference.
PLUGIN_RESOURCES = ("connector", "api-endpoint", "type-map", "shared")

HEADER = """<!-- GENERATED by scripts/render_advisory.py — do not edit.
     Run `python scripts/render_advisory.py write` to regenerate. -->

# Cross-field contract rules (advisory registry)

Relational rules that stock JSON Schema cannot express — set-equality,
disjointness, membership, cross-key uniqueness between sibling values. They are
**enforced by the validator**, so you do not need to memorize them; this file
exists so prose can cite a rule by id (`ADV-ENDP-009`) instead of restating it
and drifting.

Rendered from `analitiq.contracts.shared.advisory.all_rules()` in the pinned
`analitiq-contract-models` package — the same registry the validator enforces.
Findings for these rules surface under `validator: "contract-model"`.

Scope: the resources this plugin authors ({resources}). Pipeline, stream,
connection, and database-endpoint rules are excluded — they belong to other
tools, and database endpoints are generated at runtime by the connector's
`resource_discovery`, never authored here.

**{count} rules** across {sections} resources.
"""


def _load_rules():
    from analitiq.contracts.shared.advisory import all_rules

    return [r for r in all_rules() if r.resource in PLUGIN_RESOURCES]


def render() -> str:
    rules = _load_rules()
    by_resource: dict[str, list] = {}
    for rule in rules:
        by_resource.setdefault(rule.resource, []).append(rule)

    # Stable ordering: resources in the declared scope order, rules by id.
    sections = [r for r in PLUGIN_RESOURCES if r in by_resource]

    out = [
        HEADER.format(
            resources=", ".join(f"`{r}`" for r in PLUGIN_RESOURCES),
            count=len(rules),
            sections=len(sections),
        )
    ]

    for resource in sections:
        out.append(f"\n## {resource}\n")
        out.append("| ID | Rule | Enforced on |\n|---|---|---|\n")
        for rule in sorted(by_resource[resource], key=lambda r: r.id):
            targets = ", ".join(f"`{t}`" for t in rule.targets) if rule.targets else "—"
            prose = rule.prose.replace("|", "\\|")
            out.append(f"| {rule.id} | {prose} | {targets} |\n")

    return "".join(out)


def main(argv: list[str]) -> int:
    mode = argv[1] if len(argv) > 1 else "check"
    if mode not in ("write", "check"):
        print(f"usage: {argv[0]} [write|check]", file=sys.stderr)
        return 2

    rendered = render()

    if mode == "write":
        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_PATH.write_text(rendered, encoding="utf-8")
        print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
        return 0

    if not OUTPUT_PATH.exists():
        print(f"{OUTPUT_PATH} is missing — run `render_advisory.py write`", file=sys.stderr)
        return 1
    if OUTPUT_PATH.read_text(encoding="utf-8") != rendered:
        print(
            f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is stale — "
            "run `python scripts/render_advisory.py write`",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
